on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - develop
      - main

name: Format and Test

env:
  OTP_VERSION: "25.3.2.9"
  ELIXIR_VERSION: "1.15.7"
  MIX_ENV: "test"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: postgres

jobs:
  deps:
    name: Setup project dependencies
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup environment
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}-${{ hashFiles('config/config.exs') }}-${{ hashFiles('config/dev.exs') }}-${{ hashFiles('config/prod.exs') }}-${{ hashFiles('config/runtime.exs') }}-${{ hashFiles('config/shared_variables.exs') }}-${{ hashFiles('config/test.exs') }}

      - name: Install dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile

  format:
    name: Check format
    runs-on: ubuntu-latest
    environment: test
    needs:
      - deps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup environment
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}-${{ hashFiles('config/config.exs') }}-${{ hashFiles('config/dev.exs') }}-${{ hashFiles('config/prod.exs') }}-${{ hashFiles('config/runtime.exs') }}-${{ hashFiles('config/shared_variables.exs') }}-${{ hashFiles('config/test.exs') }}

      - name: Mix Format
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo --strict

  test:
    name: Executing tests
    runs-on: ubuntu-latest
    environment: test
    needs:
      - deps
    services:
      test_db:
        image: postgres:12
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup environment
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}-${{ hashFiles('config/config.exs') }}-${{ hashFiles('config/dev.exs') }}-${{ hashFiles('config/prod.exs') }}-${{ hashFiles('config/runtime.exs') }}-${{ hashFiles('config/shared_variables.exs') }}-${{ hashFiles('config/test.exs') }}

      - name: Run tests
        run: MIX_ENV=test mix test
